# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BLLACEmployee' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BLLACEmployee
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
  pod 'GTMOAuth2', '~> 1.1.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'BLLACEmployeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BLLACEmployeeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
